[package]
name = "file_menu_simple"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#gtk = { version = "0.5.5", package = "gtk4", features = ["v4_6"] }
gtk = "0.17.0"
gio = "0.17.0"
glib = "0.17.1"