buttons:
  - name: button1
    command: ls -lh
  - name: button2
    command: lsb_release -d
  - name: button3
    command: sensors -u
  - name: button4
    command: ls -lh
  - name: button5
    command: lsb_release -d
  - name: button6
    command: sensors -u
  - name: button7
    command: ls -lh
  - name: button8
    command: lsb_release -d
  - name: button9
    command: sensors -u
  - name: button10
    command: ls -lh
  - name: button1
    command: ls -lh
  - name: button2
    command: lsb_release -d
  - name: button3
    command: sensors -u
  - name: button4
    command: ls -lh
  - name: button5
    command: lsb_release -d
  - name: button6
    command: sensors -u
  - name: button7
    command: ls -lh
  - name: button8
    command: lsb_release -d
  - name: button9
    command: sensors -u
  - name: button10
    command: ls -lh
  - name: button1
    command: ls -lh
  - name: button2
    command: lsb_release -d
  - name: button3
    command: sensors -u
  - name: button4
    command: ls -lh
  - name: button5
    command: lsb_release -d
  - name: button6
    command: sensors -u
  - name: button7
    command: ls -lh
  - name: button8
    command: lsb_release -d
  - name: button9
    command: sensors -u
  - name: button10
    command: ls -lh
  - name: button1
    command: ls -lh
  - name: button2
    command: lsb_release -d
  - name: button3
    command: sensors -u
  - name: button4
    command: ls -lh
  - name: button5
    command: lsb_release -d
  - name: button6
    command: sensors -u
  - name: button7
    command: ls -lh
  - name: button8
    command: lsb_release -d
  - name: button9
    command: sensors -u
  - name: button10
    command: ls -lh
  - name: button1
    command: ls -lh
  - name: button2
    command: lsb_release -d
  - name: button3
    command: sensors -u
  - name: button4
    command: ls -lh
  - name: button5
    command: lsb_release -d
  - name: button6
    command: sensors -u
  - name: button7
    command: ls -lh
  - name: button8
    command: lsb_release -d
  - name: button9
    command: sensors -u
  - name: button10
    command: ls -lh
  - name: button1
    command: ls -lh
  - name: button2
    command: lsb_release -d
  - name: button3
    command: sensors -u
  - name: button4
    command: ls -lh
  - name: button5
    command: lsb_release -d
  - name: button6
    command: sensors -u
  - name: button7
    command: ls -lh
  - name: button8
    command: lsb_release -d
  - name: button9
    command: sensors -u
  - name: button10
    command: ls -lh
  - name: button1
    command: ls -lh
  - name: button2
    command: lsb_release -d
  - name: button3
    command: sensors -u
  - name: button4
    command: ls -lh
  - name: button5
    command: lsb_release -d
  - name: button6
    command: sensors -u
  - name: button7
    command: ls -lh
  - name: button8
    command: lsb_release -d
  - name: button9
    command: sensors -u
  - name: button10
    command: ls -lh
  - name: button1
    command: ls -lh
  - name: button2
    command: lsb_release -d
  - name: button3
    command: sensors -u
  - name: button4
    command: ls -lh
  - name: button5
    command: lsb_release -d
  - name: button6
    command: sensors -u
  - name: button7
    command: ls -lh
  - name: button8
    command: lsb_release -d
  - name: button9
    command: sensors -u
  - name: button10
    command: ls -lh
  - name: button1
    command: ls -lh
  - name: button2
    command: lsb_release -d
  - name: button3
    command: sensors -u
  - name: button4
    command: ls -lh
  - name: button5
    command: lsb_release -d
  - name: button6
    command: sensors -u
  - name: button7
    command: ls -lh
  - name: button8
    command: lsb_release -d
  - name: button9
    command: sensors -u
  - name: button10
    command: ls -lh
  - name: button1
    command: ls -lh
  - name: button2
    command: lsb_release -d
  - name: button3
    command: sensors -u
  - name: button4
    command: ls -lh
  - name: button5
    command: lsb_release -d
  - name: button6
    command: sensors -u
  - name: button7
    command: ls -lh
  - name: button8
    command: lsb_release -d
  - name: button9
    command: sensors -u
  - name: button10
    command: ls -lh
  - name: button1
    command: ls -lh
  - name: button2
    command: lsb_release -d
  - name: button3
    command: sensors -u
  - name: button4
    command: ls -lh
  - name: button5
    command: lsb_release -d
  - name: button6
    command: sensors -u
  - name: button7
    command: ls -lh
  - name: button8
    command: lsb_release -d
  - name: button9
    command: sensors -u
  - name: button10
    command: ls -lh
  - name: button1
    command: ls -lh
  - name: button2
    command: lsb_release -d
  - name: button3
    command: sensors -u
  - name: button4
    command: ls -lh
  - name: button5
    command: lsb_release -d
  - name: button6
    command: sensors -u
  - name: button7
    command: ls -lh
  - name: button8
    command: lsb_release -d
  - name: button9
    command: sensors -u
  - name: button10
    command: ls -lh
  - name: button1
    command: ls -lh
  - name: button2
    command: lsb_release -d
  - name: button3
    command: sensors -u
  - name: button4
    command: ls -lh
  - name: button5
    command: lsb_release -d
  - name: button6
    command: sensors -u
  - name: button7
    command: ls -lh
  - name: button8
    command: lsb_release -d
  - name: button9
    command: sensors -u
  - name: button10
    command: ls -lh
  - name: button1
    command: ls -lh
  - name: button2
    command: lsb_release -d
  - name: button3
    command: sensors -u
  - name: button4
    command: ls -lh
  - name: button5
    command: lsb_release -d
  - name: button6
    command: sensors -u
  - name: button7
    command: ls -lh
  - name: button8
    command: lsb_release -d
  - name: button9
    command: sensors -u
  - name: button10
    command: ls -lh
  - name: button1
    command: ls -lh
  - name: button2
    command: lsb_release -d
  - name: button3
    command: sensors -u
  - name: button4
    command: ls -lh
  - name: button5
    command: lsb_release -d
  - name: button6
    command: sensors -u
  - name: button7
    command: ls -lh
  - name: button8
    command: lsb_release -d
  - name: button9
    command: sensors -u
  - name: button10
    command: ls -lh
  - name: button1
    command: ls -lh
  - name: button2
    command: lsb_release -d
  - name: button3
    command: sensors -u
  - name: button4
    command: ls -lh
  - name: button5
    command: lsb_release -d
  - name: button6
    command: sensors -u
  - name: button7
    command: ls -lh
  - name: button8
    command: lsb_release -d
  - name: button9
    command: sensors -u
  - name: button10
    command: ls -lh
  - name: button1
    command: ls -lh
  - name: button2
    command: lsb_release -d
  - name: button3
    command: sensors -u
  - name: button4
    command: ls -lh
  - name: button5
    command: lsb_release -d
  - name: button6
    command: sensors -u
  - name: button7
    command: ls -lh
  - name: button8
    command: lsb_release -d
  - name: button9
    command: sensors -u
  - name: button10
    command: ls -lh
  - name: button1
    command: ls -lh
  - name: button2
    command: lsb_release -d
  - name: button3
    command: sensors -u
  - name: button4
    command: ls -lh
  - name: button5
    command: lsb_release -d
  - name: button6
    command: sensors -u
  - name: button7
    command: ls -lh
  - name: button8
    command: lsb_release -d
  - name: button9
    command: sensors -u
  - name: button10
    command: ls -lh
  - name: button1
    command: ls -lh
  - name: button2
    command: lsb_release -d
  - name: button3
    command: sensors -u
  - name: button4
    command: ls -lh
  - name: button5
    command: lsb_release -d
  - name: button6
    command: sensors -u
  - name: button7
    command: ls -lh
  - name: button8
    command: lsb_release -d
  - name: button9
    command: sensors -u
  - name: button10
    command: ls -lh
  - name: button1
    command: ls -lh
  - name: button2
    command: lsb_release -d
  - name: button3
    command: sensors -u
  - name: button4
    command: ls -lh
  - name: button5
    command: lsb_release -d
  - name: button6
    command: sensors -u
  - name: button7
    command: ls -lh
  - name: button8
    command: lsb_release -d
  - name: button9
    command: sensors -u
  - name: button10
    command: ls -lh


